### ISSUE TITLE
Ansible Module

### ISSUE THREAD

**Issue by rabin-io** [thombashi/tcconfig#126]
Hi, 

First I like to thank you for this project, which make working with `tc`  much more sane for us mortals. 

One thing I like to ask is if you would consider porting the code base into an Ansible Module ?
I started testing this with a client side support where `tcconfig` is installed on the destination machine. And [I have as small lib](https://gist.github.com/rabin-io/d470f81a47f92fca1180d1d451a23863) which I was able to compile from several places which tried  to do the same, which works for my small use case, but I think that having the support directly as ansible module/lib which compile the commands on the managing host and push the required commands to the provisioned machine is the right why to accomplish this. 

```yaml
---
- hosts: all
  become: True
  user: vagrant
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:

    - tc:
        device: eth1
        loss: 30%
        delay: 70ms
        delay_distro: 30ms
        dst_network: 192.168.56.202
```
